### ISSUE TITLE
Cannot change state of pihole

### ISSUE THREAD

**Issue by Kiwifranky** [naimo84/node-red-contrib-pi-hole-remote#25]
Hi,

I just tested it with two versions of pihole (5.0 and 5.6) - Neither is working.
I can see some of the numbers that are right, but it always shows "disabled" even when pihole is active.
I also cannot change the state in either way.

I suggest the "auth code" should be titled "api key" to match it with pihole.
I tried it with my password first and then with the api key (I guess that is right by looking to your supplied sample)

Am I doing something wrong?

Help is appreciated!

**Comment by naimo84** [comment]
HI @Kiwifranky, 

I've published a new version with your suggestions ;) And perhaps some improvements that my solve your problem.
I called it "auth code", because the pi-hole webapi also calls it "auth". But you're right, it's the api key.

Can you provide me some more informations, how your config looks like? Or even better, export your config and send me. Here or via mail. as you like :)

Regards,
Benjmamin

**Comment by Kiwifranky** [comment]
Hi Benjamin,

tested it and it works like a charm now!
Thanks for your effort.

Regards,
Frank
